# This setup is for testing only, all communication with 
# etcd is done through the proxy. You have to create a proxy
# with toxiproxy-cli before you can connect to etcd
#
# toxiproxy-cli create etcd --listen 0.0.0.0:2379 --upstream etcd:22379

version: '3.2'
services:
  etcd:
    image: quay.io/coreos/etcd:v3.2
    command: >
        /usr/local/bin/etcd
        -name etcd0
        -advertise-client-urls http://localhost:2379
        -listen-client-urls http://0.0.0.0:22379
        -initial-advertise-peer-urls http://0.0.0.0:2381
        -listen-peer-urls http://0.0.0.0:2381
        -initial-cluster-token etcd-cluster-1
        -initial-cluster etcd0=http://0.0.0.0:2381
        -initial-cluster-state new
        -enable-v2=false
    ports:
        - "22379:22379"
  proxy:
    image: shopify/toxiproxy:latest
    ports:
      - "2379:2379"
      - "8474:8474"
